name: Build and Deploy Documentation Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

# Allow one concurrent deployment
concurrency: preview-${{ github.ref }}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r docs/requirements.txt

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build with mkdocs
        run: |
          cd docs
          mkdocs build -c

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/site
